### ISSUE TITLE
Make A Chrome Extension

### ISSUE THREAD

**Issue by jamesthompson275** [jamesthompson275/YoutubeRandomiser#1]
- [x] Follow a tutorial for setting up  a chrome extension.
- [x] Implement song highlighting.
- [x] Allow turning on and off options/triggers via extension options.
- [x] Implement Song Randomisation.
- [x] Implement Drag and Drop Rearrangement.
- [x] Design an icon.
- [x] Upload it to the Web Store

**Comment by CPonty** [comment]
Done
